### ISSUE TITLE
`cache load-dump` needs refactoring

### ISSUE THREAD

**Issue by egecelikci** [RustyNova016/Alistral#282]
https://github.com/metabrainz/listenbrainz-server/pull/2954

**Comment by RustyNova016** [comment]
The whole app need refactoring 🙃
I did see the new export and it finally unblocks me too, but I didn't had time to get to it as I was finishing another part of the SQLite refactor.

If it blocks someone then I can do it for a 0.2.3 version, but it ain't happening until 0.3.0.
